export const TEST = "TEST";

export const CHANGE_USER_NAME = "CHANGE_USER_NAME";
export const CHANGE_USER_ICON = "CHANGE_USER_ICON";
export const TWEAK_USER_DIALOG = "TWEAK_USER_DIALOG";

export const SUBMIT_USER_QUESTION = "SUBMIT_USER_QUESTION";
export const GET_CHATBOT_ANSWER = "GET_CHATBOT_ANSWER";
export const RESTART_CHAT = "RESTART_CHAT";
